# Generated by Django 6.0.3 on 2026-04-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehistory',
            name='control_high_count',
        ),
        migrations.RemoveField(
            model_name='teachercoursehistory',
            name='control_high_count',
        ),
        migrations.AddField(
            model_name='coursehistory',
            name='control_avg_score',
            field=models.FloatField(default=80.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachercoursehistory',
            name='control_avg_score',
            field=models.FloatField(default=80.5),
            preserve_default=False,
        ),
    ]
