# Generated by Django 6.0.3 on 2026-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0002_remove_coursehistory_control_high_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursehistory',
            name='avg_ai_score',
        ),
        migrations.RemoveField(
            model_name='teachercoursehistory',
            name='ai_score',
        ),
        migrations.AlterField(
            model_name='coursehistory',
            name='avg_student_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursehistory',
            name='control_avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursehistory',
            name='section_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semesterhistory',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semesterhistory',
            name='section_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semesterhistory',
            name='teacher_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachercoursehistory',
            name='control_avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachercoursehistory',
            name='student_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherloadhistory',
            name='managed_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherloadhistory',
            name='total_training_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
