# Generated by Django 6.0.3 on 2026-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_career_career_faculty_abbr_idx_and_more'),
        ('historical', '0003_remove_ai_scores_nullable_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursehistory',
            index=models.Index(fields=['course', 'semester'], name='chist_crs_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercoursehistory',
            index=models.Index(fields=['teacher', 'semester'], name='tchist_tchr_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercoursehistory',
            index=models.Index(fields=['teacher', 'course'], name='tchist_tchr_crs_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherloadhistory',
            index=models.Index(fields=['teacher', 'semester'], name='tlhist_tchr_sem_idx'),
        ),
    ]
