# Generated by Django 6.0.3 on 2026-03-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
