# Generated by Django 6.0.3 on 2026-03-21 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_merge_20260318_2227'),
        ('files', '0002_alter_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('ceat', 'CEAT'), ('comments', 'Comentarios'), ('control', 'Control docente'), ('evaluation', 'Evaluacion docente'), ('pensum', 'Pensum')], max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
        ),
    ]
