# Generated by Django 6.0.3 on 2026-04-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_format_alter_file_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='archivo_ejemplo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
