# Generated by Django 6.0.3 on 2026-04-12 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_course_credits'),
        ('files', '0004_file_name_alter_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('ceat', 'CEAT'), ('comments', 'Comentarios'), ('control', 'Control docente'), ('evaluation', 'Evaluacion docente'), ('pensum', 'Pensum'), ('roster', 'Nomina')], max_length=20),
        ),
    ]
