web: gunicorn api.wsgi:application --bind 0.0.0.0:$PORT --workers 2
worker: celery -A api worker -l info --pool=prefork --concurrency=2
beat: celery -A api beat -l info
release: python manage.py migrate
