# Generated by Django 6.0.3 on 2026-03-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0008_remove_coursesection_assigned_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_count', models.IntegerField()),
                ('medium_count', models.IntegerField()),
                ('low_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('submitted_count', models.IntegerField()),
                ('assigned_students', models.IntegerField()),
                ('performance_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiation_count', models.IntegerField()),
                ('transition_count', models.IntegerField()),
                ('autonomy_count', models.IntegerField()),
                ('complementary_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacher')),
            ],
        ),
    ]
