# Generated by Django 6.0.3 on 2026-03-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('number', models.IntegerField()),
                ('ceat_loaded', models.BooleanField(default=False)),
                ('comments_loaded', models.BooleanField(default=False)),
                ('control_loaded', models.BooleanField(default=False)),
                ('evaluation_loaded', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processed', 'Processed'), ('archived', 'Archived')], default='uploading', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
