# Generated by Django 6.0.3 on 2026-03-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculty'),
        ),
    ]
