# Generated by Django 6.0.3 on 2026-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pensum_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
