# Generated by Django 6.0.3 on 2026-03-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_semester_faculty'),
    ]

    operations = []
