# Generated by Django 6.0.3 on 2026-03-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_faculty_pensum_loaded'),
        ('academics', '0004_faculty_pensum_loaded'),
    ]

    operations = [
    ]
