# Generated by Django 6.0.3 on 2026-03-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_coursesection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='assigned_students',
        ),
    ]
