# Generated by Django 6.0.3 on 2026-04-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='control_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='roster_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
