# Generated by Django 6.0.3 on 2026-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_course_add_faculty_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='appointment_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('course', 'section_number', 'shift')},
        ),
    ]
