# Generated by Django 6.0.3 on 2026-04-29 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_coursesection_appointment_credits_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_active',
        ),
    ]
