# Generated by Django 6.0.3 on 2026-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_teacher_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['faculty', 'abbreviation'], name='career_faculty_abbr_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['teacher', 'faculty'], name='contract_teacher_faculty_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['faculty', 'is_active'], name='contract_faculty_active_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['faculty', 'name'], name='course_faculty_name_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['course', 'semester'], name='cs_crs_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['appointment_number'], name='coursesection_appointment_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['faculty', 'year', 'number'], name='sem_fac_yr_num_idx'),
        ),
    ]
