# Generated by Django 6.0.3 on 2026-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_career_career_faculty_abbr_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
