# Generated by Django 6.0.3 on 2026-05-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_course_careers_m2m_and_section_career_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['faculty', 'is_active'], name='course_faculty_active_idx'),
        ),
    ]
