# Generated by Django 6.0.3 on 2026-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_course_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('name', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('teacher', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'faculty')},
        ),
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('appointment_number', 'semester'), ('course', 'section_number', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'number', 'faculty')},
        ),
    ]
