# Generated by Django 6.0.3 on 2026-03-23 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0007_coursesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('median_score', models.FloatField()),
                ('evaluation_count', models.IntegerField()),
                ('submitted_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAnalysisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
                ('comment_overview', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
    ]
