# Generated by Django 6.0.3 on 2026-05-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_teacher_is_active'),
        ('analytics', '0002_teacheranalysisai_perception_delete_sectionstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAnalysisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_overview', models.TextField(blank=True, max_length=50, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('perception', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherCommentAnalysisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
                ('comment_overview', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=50, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('perception', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfileAnalysisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_overview', models.TextField(blank=True, max_length=50, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('perception', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherAnalysisAI',
        ),
    ]
