# Generated by Django 6.0.3 on 2026-05-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_courseanalysisai_teachercommentanalysisai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseanalysisai',
            name='title',
            field=models.CharField(default='Default Title', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofileanalysisai',
            name='title',
            field=models.CharField(default='Default Title', max_length=40),
            preserve_default=False,
        ),
    ]
