# Generated by Django 6.0.3 on 2026-05-02 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_teacher_is_active'),
        ('analytics', '0004_courseanalysisai_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseanalysisai',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherprofileanalysisai',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseanalysisai',
            name='course_overview',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofileanalysisai',
            name='profile_overview',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TeacherCommentsAnalysisAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_score', models.FloatField()),
                ('comment_overview', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=100, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('perception', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursesection')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherCommentAnalysisAI',
        ),
    ]
