# Generated by Django 6.0.3 on 2026-05-02 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_teacher_is_active'),
        ('analytics', '0005_courseanalysisai_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachercommentsanalysisai',
            name='course_section',
        ),
        migrations.AddField(
            model_name='teachercommentsanalysisai',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.teacher'),
            preserve_default=False,
        ),
    ]
