# Generated by Django 6.0.3 on 2026-05-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_remove_teachercommentsanalysisai_course_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachercommentsanalysisai',
            name='negative_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teachercommentsanalysisai',
            name='neutral_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teachercommentsanalysisai',
            name='positive_percentage',
            field=models.FloatField(default=0),
        ),
    ]
