# Generated by Django 6.0.3 on 2026-05-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_teacher_is_active'),
        ('analytics', '0007_teachercommentsanalysisai_negative_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGeneralRecomendationsAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation', models.TextField(blank=True, max_length=100, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherGeneralRecomendationsAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation', models.TextField(blank=True, max_length=100, null=True)),
                ('model_version', models.CharField(max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
        ),
    ]
