# Generated by Django 6.0.3 on 2026-05-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_career_career_faculty_abbr_idx_and_more'),
        ('analytics', '0008_coursegeneralrecomendationsai_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseanalysisai',
            index=models.Index(fields=['course', 'semester'], name='cai_crs_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercommentsanalysisai',
            index=models.Index(fields=['teacher', 'semester'], name='tcai_tchr_sem_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherprofileanalysisai',
            index=models.Index(fields=['teacher', 'semester'], name='profile_teacher_semester_idx'),
        ),
    ]
