# Generated by Django 6.0.3 on 2026-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_courseanalysisai_cai_crs_sem_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseanalysisai',
            name='perception',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='teachercommentsanalysisai',
            name='perception',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], default='neutral', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofileanalysisai',
            name='perception',
            field=models.CharField(choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], default='neutral', max_length=20),
        ),
    ]
